### ISSUE TITLE
Request failed with status code 404

### ISSUE THREAD

**Issue by bermudalocket** [abskmj/hukum#1]
I couldn't quite get this to work. I have a Swift package hosted on GitHub (in a private repo) with a build workflow configured. I created `.hukumrc` and added a new token that I configured to have workflow/actions access. I pushed a commit and ran `hukum`. This was the result:

```
❯ hukum
{
  branch: 'main',
  hash: '[redacted]',
  author: '[redacted]',
  repo: 'bermudalocket/[redacted]'
}
Error: Request failed with status code 404
    at createError (/usr/local/lib/node_modules/hukum/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/hukum/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/hukum/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1224:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

[snip]
```

My first thought is the branch name. Is hukum looking for a "master" branch maybe? My repo is new and is named "main" instead.

**Comment by abskmj** [comment]
It is designed to work with any branch name. It reads the current branch name from local git and looks for the latest run on Github.

But, I haven't specifically tested with a private repository. Let me try that out and see what is missing.

**Comment by abskmj** [comment]
I got to know that others were able to use Hukum with their private repository. Can you try installing the new version 1.1.0? Hukum is now configured to print a message with the GitHub token is not set. Let me know if you are seeing the message.

**Comment by bermudalocket** [comment]
This was my fault. I somehow missed giving the access token permission to access my workflows... 😅

All fixed. Hukum works great, thank you!
